// src/components/Header/Header.tsx
import { FC } from 'react';
import { Logo } from '@/components/Logo/Logo';
import { TopBar } from '@/components/TopBar/TopBar';
import { Menu } from '@/components/Menu/Menu';

import styles from './header.module.scss';

const Header: FC = () => {
    return (
        <header className={styles.header}>
            <div className="container">
                <div className={styles['header-wrap']}>
                    <div className={styles['header-right']}>
                        <Logo />
                    </div>

                    <div className={styles['header-left']}>
                        <TopBar />

                        <Menu />
                    </div>
                </div>
            </div>
        </header>
    );
};

export default Header;

// components/Header.vue
<script lang="ts" setup>
import Logo from '@/components/Logo';
</script>

<template>
    <header id="header" class="header">
        <div class="container">
            <div class="header-wrap">
                <div class="header-content-right">
                    <Logo />
                </div>

                <div class="header-content-left">
                    Left Data
                </div>
            </div>
        </div>
    </header>
</template>

<style lang="scss">
.header {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    width: 100%;
    min-height: 120px;
}
</style>
